Ingredient.create(name: 'lemon')
Ingredient.create(name: 'ice')
Ingredient.create(name: 'mint leaves')
Ingredient.create(name: 'cherry')
Ingredient.create(name: 'orange')
Ingredient.create(name: 'chocolate')
Ingredient.create(name: 'coffee beans')
Ingredient.create(name: 'gin')
Ingredient.create(name: 'tonic')
Ingredient.create(name: 'vodka')
Ingredient.create(name: 'rum')
Ingredient.create(name: 'scotch')
Ingredient.create(name: 'brandy')
Ingredient.create(name: 'Southern Comfort')
Ingredient.create(name: 'Jack Daniels')
Ingredient.create(name: 'cognac')
Ingredient.create(name: 'Orange bitters')
Ingredient.create(name: 'whiskey')
Ingredient.create(name: 'Vermouth')
Ingredient.create(name: 'Amaretto')
Ingredient.create(name: 'tea')
Ingredient.create(name: 'champagne')
Ingredient.create(name: 'prosecco')
Ingredient.create(name: 'Bourbon')
Ingredient.create(name: 'Tequila')
Ingredient.create(name: 'bitters')
Ingredient.create(name: 'sugar')
Ingredient.create(name: 'Kahlua')
Ingredient.create(name: 'Lime juice')
Ingredient.create(name: 'carbonated water')
Ingredient.create(name: 'Grenadine')
Ingredient.create(name: 'cranberry juice')
Ingredient.create(name: 'lemonade')
Ingredient.create(name: 'ginger')
Ingredient.create(name: 'berries')
Ingredient.create(name: 'mango')
Ingredient.create(name: 'apple cider')
Ingredient.create(name: 'tomato juice')
Ingredient.create(name: 'cola')
Ingredient.create(name: 'red wine')
Ingredient.create(name: 'white wine')
